### ISSUE TITLE
Lifeblood+Normal health damage counts as 2 hits

### ISSUE THREAD

**Issue by evelyncubes** [Dastan21/HollowKnight.PantheonsHitCounter#6]
When losing a lifeblood mask and a normal mask at the same time (from taking double damage from a boss), the hit counter counts this as 2 hits instead of 1.

**Comment by Dastan21** [comment]
Oops I forgot this issue 😢
Will try to fix asap :)

**Comment by Dastan21** [comment]
Fixed in v1.3.5, should be available on Scarab soon 👍
