### ISSUE TITLE
"Maximum Splits"  setting cannot be saved

### ISSUE THREAD

**Issue by royitaqi** [Dastan21/HollowKnight.PantheonsHitCounter#7]
Changing the setting from 3 (default) to 10 then save game and exist game, then reload game and save. The setting reverts back to 3.

![image](https://user-images.githubusercontent.com/14790745/213025808-9bb335a9-effc-42f7-9306-3615e97ea458.png)

![image](https://user-images.githubusercontent.com/14790745/213025844-b7bdc542-0129-43aa-b695-ffe9991caa3f.png)

![image](https://user-images.githubusercontent.com/14790745/213025887-a5bc6c80-acec-4691-9651-7b4a8f41ea4d.png)

![image](https://user-images.githubusercontent.com/14790745/213026075-d89e3f79-82d3-4dbd-ae5a-0091aa9d6f11.png)

![image](https://user-images.githubusercontent.com/14790745/213026186-8a1cf345-65bb-4e5b-adc4-f808012bac12.png)

mod version 1.3.4 (can also see in screenshot)

**Comment by Dastan21** [comment]
Fixed in v1.3.6 👍
